# Site settings
title: "DataBasic | Data Science Made Simple"
description: "DataBasic, a Warwick Data Science Society podcast, is all about making data science simple, cutting through the hype and providing you the information that matters for your development."
podcast-description: "DataBasic, a Warwick Data Science Society podcast, is all about making data science simple, cutting through the hype and providing you the information that matters for your development."
url:  "https://www.databasicpodcast.com/"
baseurl: "/"
author:
  name: "Warwick Data Science Society"
  email: "podcast@wdss.io"
  url: "https://www.wdss.io"
permalink: pretty
permalink: /:title
keywords: [podcast, warwick, data, science, society, student, university, wdss, analytics, machine, learning, ai, artificial intelligence, interview, industry, career, business, audio]

#Plugins
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

#exclude: [_podcast.rss] #Ignore this, it will be used in case I decide to add rss feed

#Pagination
paginate: 5
paginate_path: "/page-:num/"

#Sass
sass:
  style: compressed
  sourcemap: never

#SEO
twitter:
  username:
  card: summary
facebook:
  app_id: 
logo: /assets/img/cover-art.png
social:
  name: 
  links:
lang: en-GB

#Podcast Metadata. Used by the RSS Feed, which currently isn't in use. So you can avoid this
podcast_title: DataBasic
podcast_author: Warwick Data Science Society
podcast_email: podcast@wdss.io
podcast_subtitle: "Data Science Made Simple"
podcast_summary: "DataBasic, a Warwick Data Science Society podcast, is all about making data science simple, cutting through the hype and providing you the information that matters for your development."
podcast_description: "DataBasic, a Warwick Data Science Society podcast, is all about making data science simple, cutting through the hype and providing you the information that matters for your development."
podcast_explicit: "no"
podcast_type: serial 
podcast_lang: en
podcast_launch: "2019-07-20" #Launch date of your podcast
podcast_copyright: "&#xA9;Alessio Franceschi"
podcast_feed: 
podcast_artwork: "/assets/img/Podcast_Cover.png"
